development:
  adapter: postgresql
  encoding: unicode
  database: hellorails5_development
  pool: 30
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: hellorails5_test
  pool: 5
  timeout: 5000

staging:
  adapter: postgresql
  encoding: unicode
  database: hellorails5
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: hellorails5
  pool: 5
  timeout: 5000
